version: "3.8"

services:

  # Agents
  rng_agent:
    image: rng_agent:1.0.0
    container_name: rng_agent
    build:
      context: .
      dockerfile: ./Dockerfile.test
    ports:
     - 7000:5000
    env_file:
      - ./tests/env_files/agent.rng.env.test
    entrypoint: ["gunicorn", "--bind", "0.0.0.0:5000", "tests.docker_entry_point:create_rng_app()"]

  max_agent:
    image: max_agent:1.0.0
    container_name: max_agent
    build:
      context: .
      dockerfile: ./Dockerfile.test
    ports:
     - 7001:5000
    env_file:
      - ./tests/env_files/agent.max.env.test
    entrypoint: ["gunicorn", "--bind", "0.0.0.0:5000", "tests.docker_entry_point:create_max_app()"]

  min_agent:
    image: min_agent:1.0.0
    container_name: min_agent
    build:
      context: .
      dockerfile: ./Dockerfile.test
    ports:
     - 7002:5000
    env_file:
      - ./tests/env_files/agent.min.env.test
    entrypoint: ["gunicorn", "--bind", "0.0.0.0:5000", "tests.docker_entry_point:create_min_app()"]

  diff_agent:
    image: diff_agent:1.0.0
    container_name: diff_agent
    build:
      context: .
      dockerfile: ./Dockerfile.test
    ports:
     - 7003:5000
    env_file:
      - ./tests/env_files/agent.diff.env.test
    entrypoint: ["gunicorn", "--bind", "0.0.0.0:5000", "tests.docker_entry_point:create_diff_app()"]

  update_endpoint:
    image: update_endpoint:1.0.0
    container_name: update_endpoint
    build:
      context: .
      dockerfile: ./Dockerfile.test
    ports:
     - 7004:5000
    env_file:
      - ./tests/env_files/endpoint.update.env.test
    entrypoint: ["gunicorn", "--bind", "0.0.0.0:5000", "tests.docker_entry_point:create_update_endpoint()"]

  # Blazegraph
  blazegraph:
    image: docker.cmclinnovations.com/blazegraph:1.0.0-SNAPSHOT
    container_name: "blazegraph_test"
    ports:
      - 27149:8080
    environment:
      BLAZEGRAPH_PASSWORD_FILE: /run/secrets/blazegraph_password
    # Add a secret to set the password for BASIC authentication
    secrets:
      - blazegraph_password

# Secrets used to set runtime passwords
secrets:
  blazegraph_password:
    file: tests/dummy_services_secrets/blazegraph_passwd.txt
