name: Maven Dependency Submission
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: 
    packages: write

jobs:
    submit-maven:
        runs-on: ubuntu-latest
        steps:
          - name: Maven Dependency Tree Dependency Submission
            uses: advanced-security/maven-dependency-submission-action@v4
            with:
                token: ${{ secrets.GITHUB_TOKEN }}
                