#
# Runs all the unit tests within the JPS Base Lib project.
#
# Author: Michael Hillman (mdhillman<@>cmclinnovations.com)
#
name: Run JPS Base Lib tests


# Trigger this workflow during pull requests to the 'main'
# branch, but ONLY when files within the library are changed.
on:
  pull_request:
    branches:
      - main
    paths:
      - src/*
      - pom.xml
      - docker/*
      - .github/scripts/maven-settings.xml
      - .github/workflows/test.yml

permissions:
  contents: read
        
# Job definitions
jobs:

  # Single job to build the EmailAgent and run its tests
  test-base-lib:
  
    # Run on latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "maven"

      # Build the code without test
      - name: Build code (no tests)
        working-directory: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -DskipTests package

      # Run all tests (even if some fail)
      - name: Run all tests
        working-directory: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: mvn -Dmaven.test.failure.ignore=true test
        
      # Produce test report
      - name: Test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test results
          path: ./target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
